# Generated by Django 3.0.5 on 2020-06-01 09:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200601_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='Amount'),
        ),
    ]
