# Generated by Django 3.0.5 on 2020-06-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200601_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
    ]
