# Generated by Django 3.0.5 on 2020-06-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_message', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
