# Generated by Django 3.0.5 on 2020-06-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
